import './globals.css'
import { Inter } from 'next/font/google'
import Header from './components/header/Header'
import Footer from './components/footer/Footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Wyatt Wingate Portfolio',
  description: 'Generated by create next app, this is a portfolio containing the works of the artist listed.',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      
      
      <body className={inter.className}>
        <Header />
        <main>{children}</main>
        <Footer />
      </body>
      
    </html>
  )
}
